import Head from "next/head";
import styles from "../styles/Home.module.css";
import Image from "next/image";
import PopUp from "./components/popUp";
import Techs from "./components/techs";
import SwitchLanguage from "./components/switch";
import english from "../cv.english.json";
import spanish from "../cv.spanish.json";
import { useEffect, useState } from "react";
import ProjectsDisplay from "./components/projectsDispay";

export default function Home() {
  const [cvJson, setCvJson] = useState(english);
  const [language, setLanguage] = useState(false); // language == true => spanish

  useEffect(() => {
    if (language) {
      setCvJson(spanish); // change to spanish
    } else {
      setCvJson(english);
    }
  }, [language]);

  const onClick = (e) => {
    e.preventDefault();
    document
      .getElementById(e.target.value)
      .scrollIntoView({ block: "start", behavior: "smooth" });
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Pedro Peyon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/button_blank" />
      </Head>

      <main className={styles.main}>
        <Image
          priority
          width="320"
          height="320"
          className={styles.perfil}
          src="/foto.png"
          alt="foto"
        />
        <div className={styles.titleDiv}>
          <h1 className={styles.title}>{cvJson.head.title[0]}</h1>
          <h1 className={styles.title}>
            {cvJson.head.title[1]}{" "}
            <a
              target="_blank "
              href="https://www.linkedin.com/in/pedro-peyon?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BSDvPCjw8SJujTRbK8UQYKA%3D%3D"
            >
              Pedro Peyon
            </a>
          </h1>
        </div>
        <p className={styles.developer}>{cvJson.head.subtitle}</p>
        <div className={styles.seconDiv}>
          <div className={styles.flexButtons}>
            {cvJson.head.buttons.map((el, i) => (
              <button key={i} value={el.value} onClick={onClick}>
                {el.text}
              </button>
            ))}
          </div>
        </div>
        <SwitchLanguage setLanguage={setLanguage}/>

        <PopUp
          onClick={onClick}
          styles={styles.botoncitos}
          buttons={cvJson.head.buttons}
        />
      </main>
      <div id="about" className={styles.aboutDiv}>
        <div className={styles.aboutMeDiv}>
          <h1>{cvJson.about.title}</h1>
          <p>
            {/* Soy un desarrollador full stack con <b>2 años de experiencia</b> en
            tecnologías como React, Node o Tailwind. Me encanta programar, sobre
            todo en proyectos que desafíen mis habilidades, para poder seguir
            creciendo como profesional. */}
            {cvJson.about.presentation[0]}
            <b>{cvJson.about.presentation[1]}</b>
            {cvJson.about.presentation[2]}
          </p>
          <h1>{cvJson.about.technologies}</h1>
          <Techs all />
        </div>
      </div>
      <div id="experience" className={styles.experienceDiv}>
        <h1>{cvJson.experience.title}</h1>
        <div className={styles.grid}>
          <a
            target="_blank "
            href="https://newtechgroup.com/"
            className={styles.flex2}
          >
            <div>
              <img
                alt="newtech"
                className={styles.newtechimg}
                src="/newtech.png"
              />
            </div>
            <div>
              <h2>
                Full stack developer - <b>Newtech Group</b>
              </h2>
              <p>{cvJson.experience.date}</p>
              <p className={styles.pNewtech}>
                {cvJson.experience.description[0]}
                <b>{cvJson.experience.description[1]}</b>
                {cvJson.experience.description[2]}
                <b>{cvJson.experience.description[3]}</b>.
              </p>
              <p>
                <b>{cvJson.experience.technologies}</b>
              </p>
              <Techs react node tailwind js ts git github />
            </div>
          </a>
        </div>
      </div>
      <div id="projects" className={styles.projectsDiv}>
        <h1>{cvJson.projects.title}</h1>
        <ProjectsDisplay projects={cvJson.projects.list}/>
      </div>
      <div id="contact" className={styles.contactMe}>
        <h1>{cvJson.contact.title}</h1>
        <div className={styles.contacts}>
          <div className={styles.contact}>
            <h2>
              <p>&rarr;</p> {cvJson.contact.my} number
            </h2>
            <a>+34 613 877 811</a>
          </div>

          <div className={styles.contact + " " + styles.izquierda}>
            <h2>
              {cvJson.contact.my} Email <p>&larr;</p>
            </h2>
            <a href="mailto:pedroagustinpeyon@gmail.com" target="_blank ">
              pedroagustinpeyon@gmail.com
            </a>
          </div>

          <div className={styles.contact}>
            <h2>
              <p>&rarr;</p> {cvJson.contact.my} Linkedin
            </h2>
            <a
              href="https://www.linkedin.com/in/pedro-peyon?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BSDvPCjw8SJujTRbK8UQYKA%3D%3D"
              target="_blank "
            >
              Pedro Peyon
            </a>
          </div>

          <div className={styles.contact + " " + styles.izquierda}>
            <h2>
              {cvJson.contact.my} Github <p>&larr;</p>
            </h2>
            <a href="https://github.com/Aguxteen" target="_blank ">
              Aguxteen
            </a>
          </div>
        </div>
      </div>

      <footer className={styles.footer}>
        {/* <img src="/foto.png" alt="Me" /> 
      <h1>Pedro Peyon</h1>  */}
        <h2>{cvJson.footer}</h2>
      </footer>
    </div>
  );
}
