import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Image from "next/image"
import PopUp from './popUp'
export default function Home() {
  
  
    const onClick =(e)=>{
      e.preventDefault()
      document.getElementById(e.target.value).scrollIntoView({block: "start", behavior: 'smooth' })
    }
  return (
    <div className={styles.container}>
      
      <Head>
        <title>Pedro Peyon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/button_blank" />
        
      </Head>
      
      <main className={styles.main}>
     
      <Image  width="320"  height="320" className={styles.perfil} src="/foto.png" alt="foto"/>
      <div className={styles.titleDiv} >
        <h1 className={styles.title}>
          Hello.</h1>
          <h1 className={styles.title}>

          i am <a target="_blank "href="https://www.linkedin.com/in/pedro-peyon?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BSDvPCjw8SJujTRbK8UQYKA%3D%3D">Pedro Peyon</a>
        </h1>
        </div>
        <p className={styles.developer}>FullStack Developer</p>
      <div className={styles.seconDiv}>
        

        <button value="about" onClick={onClick}>About Me</button>
        <button value="skills" onClick={onClick}>My skills</button>
        <button value="projects" onClick={onClick}>My projects</button>
        <button value="contact" onClick={onClick}>Contact Me</button>
        
          
        </div>
       
        <PopUp onClick={onClick} styles={styles.botoncitos}/>
        
        </main>
        <div id='about'  className={styles.aboutDiv}>

          <div className={styles.aboutMeDiv} >
            <h1>About me</h1>
              <p> I am a full stack developer with experience in developing web applications
                in teams and independently, with total availability for teamwork. My main goal
                  is to work for a team that helps me to develop as a professional where I would
                  contribute 100% of my effort to the development of the project. 
              </p>
              <div className={styles.centrar}>
              <a download="CV_Pedro_Peyon" href="/CV_Pedro_Peyon_ENGLISH.pdf" className={styles.buttonCV} >Download full CV</a>  
              </div>
              
            <h2>Studies</h2>
              <p>Most of my knowledge comes from the Soy Henry Bootcamp, where I had to do 2
                main projects that consisted of creating functional applications using APIs and databases.
                  In this bootcamp I also learned about teamwork and trained my soft skills.
              </p>
              <div className={styles.divImagenesStudies}>
              <img src="/Henry.png" alt="henry"/>
              <img src="/UTN_logo.png" alt="Utn"/>
              </div>
          </div>
          
          


          <div id="skills" className={styles.skillsDiv}>
          <h1>My skills</h1>
        <div className={styles.divBlanco}>
          <div className={styles.divImagenesSkills}>
          <div className={styles.flex}>
             <img src="/react.png" alt="React"/>
             <p>React</p>

          </div>
          <div className={styles.flex}>
            <img src="/redux.png" alt="Redux"/>
            <p>Redux</p>
            </div>
          
          <div className={styles.flex}>
            <img src="/js.png" alt="Js"/>
            <p>JavaScript</p>

          </div>
          
          

          
            </div>
          <div className={styles.divImagenesSkills}>
          <div className={styles.flex}>
            <img src="/html.png" alt="Html"/>
            <p>HTML</p>

          </div>

          <div className={styles.flex}>
            <img src="/css.png" alt="Css"/>
            <p>CSS</p>

          </div>
          <div className={styles.flex}>

            <img src="/nodejs.png" alt="Nodejs"/>
            <p>Node.js</p>

          </div>
          
          
            </div>
          <div className={styles.divImagenesSkills}>
          <div className={styles.flex}>
            <img src="/express.png" alt="Express"/>
            <p>Express</p>

          </div>
          <div className={styles.flex}>
            <img src="/postgres.png" alt="Postgres"/>
            <p>PostgreSQL</p>

          </div>
          
          <div className={styles.flex}>
            <img src="/sequelize.png" alt="Sequelize"/>
            <p>Sequelize</p>

          </div>
            </div>

          </div>
          
          </div>
        </div>
      <div id="projects" className={styles.projectsDiv}>
        <h1>My projects</h1>
        <div className={styles.grid} >
        <a target="_blank " href='https://henryhome.vercel.app/' className={styles.flex2}>
            <div><img alt="Henry-Home" className={styles.proyectos} src='/PG_Henry-Home.png'/> <p>Click to view deploy</p></div>
            <div className={styles.card}><h2>Henry Home</h2> 
              <p>FullStack App Created with other 5 programers using SCRUM metod. The app works as a bridge between the host of a house and the guest. Allow creating, review and reservate in the houses</p></div>
          </a>
            <a target="_blank " href='https://github.com/Aguxteen/PI-VideoGames' className={styles.flex2}>
              <div className={styles.card}><h2>PI Videogames</h2> 
              <p>FullStack App about videogames where you can find, filter, order, and create videogames using information from an API</p></div>
               <div><img  alt="Videogames" className={styles.proyectos} src='/PI_videogames.png'/> <p>Click to view code</p></div>
            </a>
          
        </div>
        
      </div>



        {/* <div  className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div> */}

        <div id='contact' className={styles.contactMe}>
          <h1> You can contact me through </h1>
          <div className={styles.contacts}>

          <div className={styles.contact}>
          <h2><p>&rarr;</p> My number</h2>
          <a>+54 9 11 6584 7963</a>
          </div>
            
          <div className={styles.contact +" "+ styles.izquierda } >
          <h2>My Email <p>&larr;</p></h2>
          <a href='mailto:pedroagustinpeyon@gmail.com' target="_blank " >pedroagustinpeyon@gmail.com</a>
          </div>

          <div className={styles.contact} >
          <h2><p>&rarr;</p> My Linkedin</h2>
          <a href='https://www.linkedin.com/in/pedro-peyon?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BSDvPCjw8SJujTRbK8UQYKA%3D%3D' target="_blank " >Pedro Peyon</a>
          </div>
          
          <div className={styles.contact +" "+ styles.izquierda }>
          <h2>My Github <p>&larr;</p></h2>
          <a href='https://github.com/Aguxteen' target="_blank " >Aguxteen</a>
          </div>




            </div>
          </div>
      
          
      <footer className={styles.footer}>
      {/* <img src="/foto.png" alt="Me" /> 
      <h1>Pedro Peyon</h1>  */}
        <h2>Thank you for your time</h2>
        
            
      </footer>

    </div>
  )
}
